// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenMinhKhai_PRN232_A01_BE.sln.Data;

#nullable disable

namespace NguyenMinhKhai_PRN232_A01_BE.sln.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250604035935_SeedStaffAccounts")]
    partial class SeedStaffAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            Email = "admin@FUNewsManagementSystem.org",
                            FullName = "System Administrator",
                            Password = "@@abc123@@",
                            Role = 0
                        },
                        new
                        {
                            AccountId = 2,
                            Email = "staff1@FUNewsManagementSystem.org",
                            FullName = "Staff Member 1",
                            Password = "Staff123@@",
                            Role = 1
                        },
                        new
                        {
                            AccountId = 3,
                            Email = "staff2@FUNewsManagementSystem.org",
                            FullName = "Staff Member 2",
                            Password = "Staff123@@",
                            Role = 1
                        },
                        new
                        {
                            AccountId = 4,
                            Email = "staff3@FUNewsManagementSystem.org",
                            FullName = "Staff Member 3",
                            Password = "Staff123@@",
                            Role = 1
                        });
                });

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NewsId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NewsId")
                        .HasColumnType("int");

                    b.HasKey("TagId");

                    b.HasIndex("NewsId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.News", b =>
                {
                    b.HasOne("NguyenMinhKhai_PRN232_A01_BE.sln.Models.Account", "Account")
                        .WithMany("NewsArticles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NguyenMinhKhai_PRN232_A01_BE.sln.Models.Category", "Category")
                        .WithMany("NewsArticles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.Tag", b =>
                {
                    b.HasOne("NguyenMinhKhai_PRN232_A01_BE.sln.Models.News", "News")
                        .WithMany("Tags")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("News");
                });

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.Account", b =>
                {
                    b.Navigation("NewsArticles");
                });

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.Category", b =>
                {
                    b.Navigation("NewsArticles");
                });

            modelBuilder.Entity("NguyenMinhKhai_PRN232_A01_BE.sln.Models.News", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
